### ISSUE TITLE
p100 status default on

### ISSUE THREAD

**Issue by maxeq** [artemvang/p100-go#1]
I have a problem, I really like Tapo  P100 and want to change my starting status.

My problem is that after a power outage, the p100 does not remember theprevious state and is always turned off.

How do I changeit ?  Is there any setting for a power outage?

**Comment by artemvang** [comment]
Hi, maxeq!

Unfortunately, p100 does not save the last state of its switch. But if you are planning to control your Tapo P100 with some script or daemon, you could save the last state elsewhere on your machine (Raspberry Pi in my case).

**Comment by maxeq** [comment]
Thank you very much for your answer, Artem!

Can you please suggest any script or daemon how to save the last state?

**Comment by artemvang** [comment]
You could periodically read p100 device info and store status somewhere using following code:
```
        deviceInfo, _ := device.GetDeviceInfo()
        deviceOn := deviceInfo.Result.DeviceON
        StoreDeviceStatusSomewhere(deviceOn, deviceInfo.Result.Nickname)  // it could be redis or just file
```
